spring:
  application:
    name: springboot-mybatis-quickstart
#配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/web01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#配置mybatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#指定XML映射配置文件的位置
  mapper-locations: classpath:mapper/*.xml

